### ISSUE TITLE
useGenericResponse false generates wrong return type on petstore.yml

### ISSUE THREAD

**Issue by TrisTronNL** [sschnabe/micronaut-openapi-codegen#8]
Hi, first of all great job on this generator. This is exactly what I was looking for.
However when setting useGenericResponse to false it doesn't seem to work for methods return List. This can be reproduced with this yaml => https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
void createPets(); & Pet showPetById(...) are correct but listPets results in: HttpResponse<java.util.List<Pet>> listPets(...).
Hope you can fix this. Thanks!

**Comment by sschnabe** [comment]
Hi, the generic response is generated because the response can have a [http header](https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/examples/v3.0/petstore.yaml). The generator checks for [this](https://github.com/sschnabe/micronaut-openapi-codegen/blob/0.8.0/src/main/java/org/openapitools/codegen/languages/MicronautCodegen.java#L187). Is a config option **forceNonGeneric** a valid solution for your usecase?

br, stephan

**Comment by TrisTronNL** [comment]
Hi thanks for the reply. I totally missed the fact that the response had a http header and that's why the response wrapper is needed. In that case the generated code is correct. No extra config option needs to be added in my opinion. I tested with my own openapi file and everything worked as expected.
